os: linux
dist: xenial
language: minimal

services:
  - docker

script:
  - printenv
  - docker images

#before_deploy:
#  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
#deploy:
#  provider: script
#  script: docker push myorg/myimage
#  on:
#    branch: master
